name: Ci - Projeto Git

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup ambiente de desenvolvimento
        run: echo "Ambiente de desenvolvimento configurado"

      - name : Verificar README.md
        run: |
          if [ ! -f README.md ]; then
            echo "README.md não encontrado!"
            exit 1
          fi

      - name: Contar linhas do projeto
        run: |
            echo "Contando linhas de código..."
            wc -l README.md

      - name: Teste de integração
        run: |
           echo "Executando testes na pipeline..."
           sleep 2
           echo "Testes concluídos com sucesso!"
           
      - name: Final
        run: echo "Pipeline de CI concluída com sucesso!"

      - name: Build Docker
        run: |
          echo "Construindo imagem Docker..."
          docker build -t projeto-git -f docker/Dockerfile .
      
      - name: Run Docker Container
        run: |
          echo "Rodando container Docker..."
          docker run -d -p 3000:3000 projeto-git

      - name: Wait app
        run: sleep 10 

      - name: Testar aplicação
        run: curl http://localhost:3000
      